[versions]
kotlin = "1.9.24"
coroutine = "1.8.1"
kotest = "5.9.1"
kotest-extension = "1.3.0"
mockk = "1.13.12"
cglib = "3.3.0"

[libraries]
coroutine = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine"}
cglib = { group = "cglib", name = "cglib", version.ref = "cglib" }
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertion = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-extension = { group = "io.kotest.extensions", name = "kotest-extensions-spring", version.ref = "kotest-extension" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
kotest = ["kotest-junit", "kotest-assertion", "kotest-extension"]
mockk = ["mockk"]
